variables:
    # we need lower case!!!
    CI_PROJECT_NAMESPACE: docker
    CONTAINER_TEST_IMAGE: docker.rz.tu-harburg.de:5000/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_PIPELINE_ID
    CONTAINER_VERSIONED_IMAGE: docker.rz.tu-harburg.de:5000/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME
    CONTAINER_RELEASE_IMAGE: docker.rz.tu-harburg.de:5000/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:latest

stages:
    - build
    - deploy

build:
    stage: build
    only:
        - tags
        - triggers
        - branches
    tags:
        - build
    script:
        - sudo docker build --pull -t $CONTAINER_TEST_IMAGE .
        - sudo docker push $CONTAINER_TEST_IMAGE
        
deploy:
    stage: deploy
    script:
        - sudo docker pull $CONTAINER_TEST_IMAGE
        - sudo docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
        - sudo docker push $CONTAINER_RELEASE_IMAGE
    tags:
        - deploy
    only:
        - triggers
        - master
        
deploy:
    stage: deploy
    script:
        - if [[ "${CI_COMMIT_REF_NAME}" =~ ^[0-9]+\.[0-9]+\.[0-9]+-{0,1}.*$ ]]; then sudo docker pull $CONTAINER_TEST_IMAGE; sudo docker tag $CONTAINER_TEST_IMAGE $CONTAINER_VERSIONED_IMAGE; sudo docker push $CONTAINER_VERSIONED_IMAGE; fi
    tags:
        - deploy
    only:
        - branches
    except:
        - master