deployment_system:
    only:
        - master
    tags:
        - master
    script:
        - docker build --no-cache -t local/humhub:$CI_PROJECT_ID.$CI_BUILD_ID .
        - docker tag local/humhub:$CI_PROJECT_ID.$CI_BUILD_ID localhost:5000/humhub:latest
        - docker push localhost:5000/humhub:latest
        - docker rmi local/humhub:$CI_PROJECT_ID.$CI_BUILD_ID