job:
    only:
        - tags
        - triggers
    tags:
        - master
    script:
        - ~/imagebuilder --no-cache --build-repo $CI_BUILD_REPO --project-dir $CI_PROJECT_DIR --project-id $CI_PROJECT_ID --build-id $CI_BUILD_ID --build-tag latest .