deployment_system:
    only:
        - master
    tags:
        - master
    script:
        - docker build --no-cache -t local/humhub:tmp_$CI_PROJECT_ID.$CI_BUILD_ID .
        - docker tag local/humhub:tmp_$CI_PROJECT_ID.$CI_BUILD_ID docker.rz.tu-harburg.de:5000/humhub:latest
        - docker push docker.rz.tu-harburg.de:5000/humhub:latest
        - docker rmi local/humhub:tmp_$CI_PROJECT_ID.$CI_BUILD_ID