humhub:
  image: 'local/humhub:1.0.1'
  restart: 'no'
  hostname: 'humhub'
  ports:
    - '50080:80'
    - '50443:443'
  external_links:
      - mariadb_mariadb_1:db
  volumes:
#    - '/docker_volumes/srv/humhub/hh1/config:/usr/local/share/humhub/config'
#    - '/docker_volumes/srv/humhub/hh1/uploads:/usr/local/share/humhub/uploads'
     - '/docker_volumes/srv/humhub/hh1:/usr/share/nginx/html'
